### ISSUE TITLE
Bump to `v1.0.1`

### ISSUE THREAD

**Issue by jeffseif** [conda-forge/untwine-feedstock#4]
I would like to use `v1.0.1` of untwine because of [its ability to set the SRS for COPC's when they aren't present in the input file](https://github.com/hobuinc/untwine/compare/1.0.0...1.0.1), but only `v1.0.0` [is available on conda-forge](https://anaconda.org/conda-forge/untwine).  Could we build a conda package for `v1.0.1` as well?

My understanding [from the conda-forge docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#example-workflow-for-updating-a-package) is that this would require bumping the version and tarball SHA in https://github.com/conda-forge/untwine-feedstock/blob/cd7cefade4c9296c8c9157dd19a9255315cf2445/recipe/meta.yaml .  Do you accept PR's to do this?  If so, I am happy to put together one.

Thank you!

CC @hobu

**Comment by hobu** [comment]
See #5

**Comment by jeffseif** [comment]
Thank you for the quick response!
